build-GlobalUtils:
    echo "Global layers build started"
    pip install --default-timeout=100 -r ./python/requirements.txt -t /tmp/samcli/artifacts/python
    echo "Global layers build completed"
    cp -r ./python /tmp/samcli/artifacts/