build-GlobalUtils:
	echo "Global layers build started"
	python3 -m pip install --default-timeout=100 -r ./python/requirements.txt -t .
	echo "Global layers build completed"
	cp -r ./python $(ARTIFACTS_DIR)/
